### ISSUE TITLE
benchmark cant auto infer by tensorflow gpu image -- another problem

### ISSUE THREAD

**Issue by priscilla-pan** [Adlik/Adlik#217]
reason：
bug in cmd_script.py 

error log：
python3 benchmark/src/automatic_test.py -d benchmark/tests/docker_test/tensorflow_gpu.Dockerfile -s tensorflow_gpu -b . -a . -m resnet50  -c benchmark/tests/client_script/resnet50_client_script.sh -ss benchmark/tests/serving_script/resnet50_serving_script.sh -l /home/pjy/adlik/Adlik/benchmark/log -tm benchmark/tests/test_model/resnet50_keras -cis imagenet_client.py -i imagenet.JPEG -cs benchmark/tests/compile_script/compile_script.sh  -sj resnet50_serving_model.json -gl 0
 
 {'status': 'success', 'path': '/home/john/Adlik/model/model_repos_imagenet_resnet50_keras/resnet50_1.zip'}
Traceback (most recent call last):
  File "/home/john/Adlik/benchmark/tests/client/imagenet_client.py", line 169, in <module>
    _main()
  File "/home/john/Adlik/benchmark/tests/client/imagenet_client.py", line 109, in _main
    context = PredictContext(FLAGS.model_name, url=FLAGS.url, protocol=FLAGS.protocol, verbose=True)
  File "/usr/local/lib/python3.6/dist-packages/adlik_serving/__init__.py", line 159, in __init__
    self._model_config = self._runner.get_model_meta(self._model_spec)
  File "/usr/local/lib/python3.6/dist-packages/adlik_serving/__init__.py", line 109, in get_model_meta
    response = self._stub.getModelMeta(request)
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1594381294.023978832","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3948,"referenced_errors":[{"created":"@1594381294.023975678","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]}"

**Comment by priscilla-pan** [comment]
when model is big，server not ready when client request
